//database.h was generated by DBGEN.EXE [1.2.0.0]
#ifndef DATABASE_ARRAY
#define DATABASE_ARRAY
#include <string>
#define \
GAME_AMOUNT \
15853
extern const std::string gamename_internal_database[GAME_AMOUNT + 1];
#endif//DATABASE_ARRAY
